In [1]:
from datetime import datetime

In [2]:
aa="""11:10:49.249 -> X= -9.00       Y= -1.00       Z= 20.00  
11:10:49.283 -> X= -8.00       Y= 0.00       Z= 22.00  
11:10:49.318 -> X= -9.00       Y= 1.00       Z= 22.00  
11:10:49.352 -> X= -7.00       Y= -1.00       Z= 21.00  
11:10:49.421 -> X= -8.00       Y= 0.00       Z= 21.00  
11:10:49.455 -> X= -8.00       Y= 1.00       Z= 21.00  
11:10:49.490 -> X= -8.00       Y= 0.00       Z= 21.00  
11:10:49.524 -> X= -9.00       Y= 1.00       Z= 21.00  
11:10:49.593 -> X= -8.00       Y= 2.00       Z= 21.00  
11:10:49.626 -> X= -8.00       Y= 1.00       Z= 25.00  
11:10:49.661 -> X= -8.00       Y= 1.00       Z= 21.00  
11:10:49.696 -> X= -9.00       Y= 0.00       Z= 21.00  
11:10:49.783 -> X= -8.00       Y= -1.00       Z= 21.00  
11:10:49.783 -> X= -8.00       Y= -1.00       Z= 22.00  
11:10:49.853 -> X= -8.00       Y= 2.00       Z= 21.00  
11:10:49.899 -> X= -8.00       Y= 0.00       Z= 24.00  
11:10:49.926 -> X= -7.00       Y= 0.00       Z= 21.00  
11:10:49.961 -> X= -8.00       Y= 0.00       Z= 21.00  
11:10:49.996 -> X= -8.00       Y= 0.00       Z= 21.00  
11:10:50.064 -> X= -8.00       Y= 0.00       Z= 20.00  
11:10:50.098 -> X= -8.00       Y= 0.00       Z= 22.00  
11:10:50.133 -> X= -7.00       Y= 1.00       Z= 26.00  
11:10:50.166 -> X= -9.00       Y= 0.00       Z= 22.00  
11:10:50.234 -> X= -8.00       Y= 0.00       Z= 23.00  
11:10:50.269 -> X= -8.00       Y= 1.00       Z= 20.00  
11:10:50.304 -> X= -9.00       Y= 2.00       Z= 21.00  
11:10:50.338 -> X= -8.00       Y= 0.00       Z= 21.00  
11:10:50.408 -> X= -8.00       Y= 1.00       Z= 22.00  
11:10:50.441 -> X= -8.00       Y= 2.00       Z= 23.00  
11:10:50.476 -> X= -8.00       Y= 0.00       Z= 22.00  
11:10:50.511 -> X= -9.00       Y= -1.00       Z= 21.00  
11:10:50.580 -> X= -8.00       Y= 0.00       Z= 21.00  
11:10:50.615 -> X= -7.00       Y= 0.00       Z= 21.00  
11:10:50.651 -> X= -8.00       Y= 1.00       Z= 21.00  
11:10:50.684 -> X= -8.00       Y= -1.00       Z= 24.00  
11:10:50.752 -> X= -8.00       Y= -1.00       Z= 21.00  
11:10:50.786 -> X= -9.00       Y= 0.00       Z= 21.00  
11:10:50.820 -> X= -7.00       Y= 0.00       Z= 21.00  
11:10:50.854 -> X= -8.00       Y= -1.00       Z= 21.00  
11:10:50.923 -> X= -8.00       Y= 1.00       Z= 21.00  
11:10:50.958 -> X= -7.00       Y= 0.00       Z= 20.00  
11:10:50.993 -> X= -8.00       Y= -1.00       Z= 21.00  
11:10:51.029 -> X= -8.00       Y= 0.00       Z= 22.00  
11:10:51.097 -> X= -9.00       Y= 1.00       Z= 20.00  
11:10:51.132 -> X= -9.00       Y= 1.00       Z= 27.00  
11:10:51.167 -> X= -9.00       Y= 1.00       Z= 20.00  
11:10:51.202 -> X= -8.00       Y= 0.00       Z= 21.00"""

In [3]:
def gen_datetime(h,m,s):
    return datetime(2018,10,6,int(h),int(m),int(s.split('.')[0]),int(s.split('.')[1])*1000)

datetime(2018,10,6)

datetime.datetime(2018, 10, 6, 0, 0)

In [16]:
def gen_datetime(L):
    return datetime(2018,10,6,int(L[0]),int(L[1]),int(L[2].split('.')[0]),int(L[2].split('.')[1])*1000)


times = list(map(gen_datetime, [row.split('->')[0].split(':')for row in aa.split('\n')]))
times

[datetime.datetime(2018, 10, 6, 11, 10, 49, 249000),
 datetime.datetime(2018, 10, 6, 11, 10, 49, 283000),
 datetime.datetime(2018, 10, 6, 11, 10, 49, 318000),
 datetime.datetime(2018, 10, 6, 11, 10, 49, 352000),
 datetime.datetime(2018, 10, 6, 11, 10, 49, 421000),
 datetime.datetime(2018, 10, 6, 11, 10, 49, 455000),
 datetime.datetime(2018, 10, 6, 11, 10, 49, 490000),
 datetime.datetime(2018, 10, 6, 11, 10, 49, 524000),
 datetime.datetime(2018, 10, 6, 11, 10, 49, 593000),
 datetime.datetime(2018, 10, 6, 11, 10, 49, 626000),
 datetime.datetime(2018, 10, 6, 11, 10, 49, 661000),
 datetime.datetime(2018, 10, 6, 11, 10, 49, 696000),
 datetime.datetime(2018, 10, 6, 11, 10, 49, 783000),
 datetime.datetime(2018, 10, 6, 11, 10, 49, 783000),
 datetime.datetime(2018, 10, 6, 11, 10, 49, 853000),
 datetime.datetime(2018, 10, 6, 11, 10, 49, 899000),
 datetime.datetime(2018, 10, 6, 11, 10, 49, 926000),
 datetime.datetime(2018, 10, 6, 11, 10, 49, 961000),
 datetime.datetime(2018, 10, 6, 11, 10, 49, 996000),
 datetime.datetime(2018, 10, 6, 11, 10, 50, 64000),
 datetime.datetime(2018, 10, 6, 11, 10, 50, 98000),
 datetime.datetime(2018, 10, 6, 11, 10, 50, 133000),
 datetime.datetime(2018, 10, 6, 11, 10, 50, 166000),
 datetime.datetime(2018, 10, 6, 11, 10, 50, 234000),
 datetime.datetime(2018, 10, 6, 11, 10, 50, 269000),
 datetime.datetime(2018, 10, 6, 11, 10, 50, 304000),
 datetime.datetime(2018, 10, 6, 11, 10, 50, 338000),
 datetime.datetime(2018, 10, 6, 11, 10, 50, 408000),
 datetime.datetime(2018, 10, 6, 11, 10, 50, 441000),
 datetime.datetime(2018, 10, 6, 11, 10, 50, 476000),
 datetime.datetime(2018, 10, 6, 11, 10, 50, 511000),
 datetime.datetime(2018, 10, 6, 11, 10, 50, 580000),
 datetime.datetime(2018, 10, 6, 11, 10, 50, 615000),
 datetime.datetime(2018, 10, 6, 11, 10, 50, 651000),
 datetime.datetime(2018, 10, 6, 11, 10, 50, 684000),
 datetime.datetime(2018, 10, 6, 11, 10, 50, 752000),
 datetime.datetime(2018, 10, 6, 11, 10, 50, 786000),
 datetime.datetime(2018, 10, 6, 11, 10, 50, 820000),
 datetime.datetime(2018, 10, 6, 11, 10, 50, 854000),
 datetime.datetime(2018, 10, 6, 11, 10, 50, 923000),
 datetime.datetime(2018, 10, 6, 11, 10, 50, 958000),
 datetime.datetime(2018, 10, 6, 11, 10, 50, 993000),
 datetime.datetime(2018, 10, 6, 11, 10, 51, 29000),
 datetime.datetime(2018, 10, 6, 11, 10, 51, 97000),
 datetime.datetime(2018, 10, 6, 11, 10, 51, 132000),
 datetime.datetime(2018, 10, 6, 11, 10, 51, 167000),
 datetime.datetime(2018, 10, 6, 11, 10, 51, 202000)]

In [15]:
def gen_datetime(L):
    return datetime(2018,10,6,int(L[0]),int(L[1]),int(L[2].split('.')[0]),int(L[2].split('.')[1])*1000)

L = "11:10:51.202 -> X= -8.00       Y= 0.00       Z= 21.00"
L = L.split('->')[0].split(':')
gen_datetime(L)

datetime.datetime(2018, 10, 6, 11, 10, 51, 202000)

In [6]:
[row.split('->')[0].split(':')for row in aa.split('\n')]

[['11', '10', '49.249 '],
 ['11', '10', '49.283 '],
 ['11', '10', '49.318 '],
 ['11', '10', '49.352 '],
 ['11', '10', '49.421 '],
 ['11', '10', '49.455 '],
 ['11', '10', '49.490 '],
 ['11', '10', '49.524 '],
 ['11', '10', '49.593 '],
 ['11', '10', '49.626 '],
 ['11', '10', '49.661 '],
 ['11', '10', '49.696 '],
 ['11', '10', '49.783 '],
 ['11', '10', '49.783 '],
 ['11', '10', '49.853 '],
 ['11', '10', '49.899 '],
 ['11', '10', '49.926 '],
 ['11', '10', '49.961 '],
 ['11', '10', '49.996 '],
 ['11', '10', '50.064 '],
 ['11', '10', '50.098 '],
 ['11', '10', '50.133 '],
 ['11', '10', '50.166 '],
 ['11', '10', '50.234 '],
 ['11', '10', '50.269 '],
 ['11', '10', '50.304 '],
 ['11', '10', '50.338 '],
 ['11', '10', '50.408 '],
 ['11', '10', '50.441 '],
 ['11', '10', '50.476 '],
 ['11', '10', '50.511 '],
 ['11', '10', '50.580 '],
 ['11', '10', '50.615 '],
 ['11', '10', '50.651 '],
 ['11', '10', '50.684 '],
 ['11', '10', '50.752 '],
 ['11', '10', '50.786 '],
 ['11', '10', '50.820 '],
 ['11', '10', '50.854 '],
 ['11', '10', '50.923 '],
 ['11', '10', '50.958 '],
 ['11', '10', '50.993 '],
 ['11', '10', '51.029 '],
 ['11', '10', '51.097 '],
 ['11', '10', '51.132 '],
 ['11', '10', '51.167 '],
 ['11', '10', '51.202 ']]